### ISSUE TITLE
==> ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by terric** [vilkoz/playkey-linux-launcher#1]
**The commands from the readme don't work**

I tried building the package for Arch Linux, using the commands from the readme:
```
git clone https://github.com/vilkoz/playkey-linux-launcher.git
cd playkey-linux-launcher
makepkg -si PKGBUILD
```
... but those didn't work. I got the following error:

```

:: Checking playkey-linux integrity...
==> Making package: playkey-linux 1.0-1 (Sun 07 Jul 2019 12:43:29 PM CEST)
==> Retrieving sources...
  -> Found PlaykeySetup.exe&name=PlaykeySetup.exe
  -> Updating playkey-linux-launcher git repo...
Fetching origin
==> Validating source_x86_64 files with sha256sums...
    PlaykeySetup.exe&name=PlaykeySetup.exe ... FAILED
    playkey-linux-launcher ... Skipped
==> ERROR: One or more files did not pass the validity check!

```

**Workaround to successfully install the package**

Instead I had to skip integrity checks when building the package.  
The makepkg command that worked for me was:

`makepkg -i --skipinteg --skipchecksums --skippgpcheck PKGBUILD`

**Comment by vilkoz** [comment]
Thank you for the report, I will update sha256sum in PKGBUILD to match updated version of the playkey installer.

**Comment by vilkoz** [comment]
Fixed

**Comment by terric** [comment]
Wow, that was quick. Thanks man!
